/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package View;

/**
 *
 * @author DMM-ADMIN
 */
public class Menu_BS_View extends javax.swing.JFrame {

    /**
     * Creates new form ElegirReporte
     */
    public Menu_BS_View() {
        initComponents();
        setLocationRelativeTo(null);
        
        this.setTitle("Elegir Reporte de Bitácora");
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        btnPCK = new javax.swing.JButton();
        btnPRS = new javax.swing.JButton();
        btnHBL = new javax.swing.JButton();
        btnBUSH = new javax.swing.JButton();
        btnRegresar = new javax.swing.JButton();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        btnPCK.setBackground(new java.awt.Color(0, 0, 153));
        btnPCK.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnPCK.setForeground(new java.awt.Color(255, 255, 255));
        btnPCK.setText("Bitácora Empaque");

        btnPRS.setBackground(new java.awt.Color(0, 0, 153));
        btnPRS.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnPRS.setForeground(new java.awt.Color(255, 255, 255));
        btnPRS.setText("Bitácora Prensa");

        btnHBL.setBackground(new java.awt.Color(0, 0, 153));
        btnHBL.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnHBL.setForeground(new java.awt.Color(255, 255, 255));
        btnHBL.setText("Bitácora HBL/PLT");

        btnBUSH.setBackground(new java.awt.Color(0, 0, 153));
        btnBUSH.setFont(new java.awt.Font("Tahoma", 0, 36)); // NOI18N
        btnBUSH.setForeground(new java.awt.Color(255, 255, 255));
        btnBUSH.setText("Bitácora Bush");
        btnBUSH.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBUSHActionPerformed(evt);
            }
        });

        btnRegresar.setBackground(new java.awt.Color(0, 0, 0));
        btnRegresar.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        btnRegresar.setForeground(new java.awt.Color(255, 255, 255));
        btnRegresar.setText("Regresar");

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                    .addComponent(btnPRS, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnHBL, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnPCK, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnBUSH, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(btnRegresar, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap(100, Short.MAX_VALUE))
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap(100, Short.MAX_VALUE)
                .addComponent(btnPCK, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnPRS, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnHBL, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnBUSH, javax.swing.GroupLayout.PREFERRED_SIZE, 65, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(37, 37, 37)
                .addComponent(btnRegresar, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(84, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnBUSHActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBUSHActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_btnBUSHActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    public javax.swing.JButton btnBUSH;
    public javax.swing.JButton btnHBL;
    public javax.swing.JButton btnPCK;
    public javax.swing.JButton btnPRS;
    public javax.swing.JButton btnRegresar;
    // End of variables declaration//GEN-END:variables
}
